--   CREATE TABLE  users (
--       userId TEXT PRIMARY KEY,
--       firstName TEXT NOT NULL,
--       lastName TEXT NOT NULL,
--       email TEXT NOT NULL UNIQUE,
--       department TEXT NOT NULL
--     );